version: '1.0'

configurations:
  default:
    restart: never
    network_mode: host
    volumes:
      - /data:/data
      - /data:/root/data
      - /code:/root/code
      # avahi socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket